server:
  port: 8787
  session:
    timeout: 72000

adminPath:

spring:
  datasource:
    url: jdbc:mysql://192.168.0.92/adevice?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull
    username: adevice
    password: 8LwF8HUAtWJ
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    validation-query: select 'x'
    test-while-idle: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates
    suffix: .html
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Chongqing

logging:
  level.com.coocaa.adevice: debug

adevice:
  adeviceSite: http://192.168.1.164